on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/*.yml"
      - "package*.json"
  workflow_dispatch:

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Behave-full-Theme-${{ github.sha }}
          path: ./*.vsix